#name: Telegram to WordPress Sync

#on:
#  schedule:
#    - cron: "0 * * * *" # Раз в час
#  workflow_dispatch:

#permissions:
#  contents: read

#env:
  TG_API_ID: ${{ secrets.TG_API_ID }}
  TG_API_HASH: ${{ secrets.TG_API_HASH }}
  TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
  TG_SESSION: ${{ secrets.TG_SESSION }}
  WP_USER: ${{ secrets.WP_USER }}
  WP_PASS: ${{ secrets.WP_PASS }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install telethon requests

      - name: Run script
        run: python sync.py
